project_id = "huztedyjmuxuxwcpniec"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322

[studio]
enabled = true
port = 54323
api_url = "http://localhost"

[inbucket]
enabled = true
port = 54324

[storage]
enabled = true
port = 54325

[auth]
enabled = true
port = 54326

[auth.external.google]
enabled = true
client_id = "env(SUPABASE_AUTH_GOOGLE_CLIENT_ID)"
secret = "env(SUPABASE_AUTH_GOOGLE_SECRET)"

[auth.external.twitter]
enabled = true
client_id = "env(SUPABASE_AUTH_TWITTER_CLIENT_ID)"
secret = "env(SUPABASE_AUTH_TWITTER_SECRET)"

[realtime]
enabled = true
port = 54327

[functions]
[functions.send-welcome-email]
verify_jwt = false

[functions.send-confirmation-email]
verify_jwt = false

